# -*- coding: utf-8 -*-
"""VaderAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkttN7MCJ_NPoVDJOPNcCWUv56KCyUjd
"""

# Import library

import nltk
nltk.download('vader_lexicon')

# Import library

from nltk.sentiment.vader import SentimentIntensityAnalyzer

sentiment = SentimentIntensityAnalyzer()

# calculating sentiment of a text, positive
# Text is 0.0% Negative, 19.2% Neutral, 80.8% Positive. While the compound score is 63.69%.

sentiment.polarity_scores("I love football.")

# calculating sentiment, negative
# Text is 78.7% Negative, 21.3% Neutral, 0.0% Positive. While the compound score is -57.19%.

print(sentiment.polarity_scores("I hate football."))

# calculating sentiment, neutral
# Text is 0.0% Negative, 100.0% Neutral, 0.0% Positive. While the compound score is 0.00%.

print(sentiment.polarity_scores("Abhishek is a footballer."))

# calculating sentiment, border case example
# Text is 26.2% Negative, 45.2% Neutral, 28.5% Positive. While the compound score is -12.80%.

print(sentiment.polarity_scores("I loved the football game but hated Cristiano Ronaldo. I guess it was a good game."))

# CASE
#Amazon Fine Food Reviews
#Measuring the sentiment

# importing libraries

import numpy as np
import nltk
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# importing libraries

import nltk
nltk.download(['punkt','stopwords'])
from nltk.corpus import stopwords
stopwords = stopwords.words('english')

#Data In- Preprocessed Data
from google.colab import files

# Upload the CSV file
uploaded = files.upload()

# already text preprocessed data in

data = pd.read_csv('Foodreview.csv')
data.head(10)

# Checking data

# 568454 rows

# 10 columns

data.shape

# checking null values

data.isnull().any().any()

data.info(null_counts=True)

data['ProfileName'].fillna('', inplace=True)
data['Summary'].fillna('', inplace=True)

#Got Rid of the Null Values
data.isnull().sum()

# calculating compound score and labeling vader scor
data['Combined'] = data['Summary'].fillna('') + ' ' + data['Text'].fillna('')

# checking data and vader score column

data.head(15)

data.drop('vader_score', axis=1, inplace=True)

from nltk.sentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

data['vader_score'] = data['Combined'].apply(lambda x: analyzer.polarity_scores(x)['compound'])

data.head(10)

# checking positive and negative

positive_num = len(data[data['vader_score'] >=0.05])

negative_num = len(data[data['vader_score']<0.05])

#positive_num,neutral_num, negative_num
positive_num, negative_num

# adding vader sentiment label column

data['vader_sentiment_label']= data['vader_score'].map(lambda x:int(1) if x>=0.05 else int(0))

data.head(10)

# checking positive, neutral and negative

positive_num = len(data[data['vader_score'] >=0.05])
neutral_num = len(data[(data['vader_score'] >-0.05) & (data['vader_score']<0.05)])
negative_num = len(data[data['vader_score']<=-0.05])

# checking positive, neutral and negative

positive_num,neutral_num, negative_num

import matplotlib.pyplot as plt

# Create a bar chart
labels = ['Positive', 'Neutral', 'Negative']
values = [positive_num, neutral_num, negative_num]

plt.bar(labels, values, color=['green', 'gray', 'red'])
plt.xlabel('Sentiment')
plt.ylabel('Number of Tweets')
plt.title('Sentiment Analysis Results')
# Add number labels on top of each bar
for i, value in enumerate(values):
    plt.text(i, value + 0.1, str(value), ha='center', va='bottom')

plt.show()

"""Based on the sentiment analysis results, you have the following distribution of tweets:
Positive Tweets: 503,480
Neutral Tweets: 7,456
Negative Tweets: 57,518
Conclusion:
The majority of the analyzed tweets express positive sentiment, with a significant number of tweets falling into the negative category.
The neutral tweets are relatively fewer in comparison. This analysis provides insights into the overall sentiment expressed in the dataset,
indicating a generally positive sentiment but with a notable presence of negative sentiment in the sampled tweets.
Further investigation into the specific content of negative tweets could provide valuable insights into areas that might require attention or improvement."""

